import pytest
import pandas as pd
import numpy as np
from tradenexus.indicators.smc import calculate_smc_lite

def test_smc_no_lookahead_all_candles():
    """
    Asserts that the Support and Resistance levels generated by SMC
    do not suffer from look-ahead bias (no-repaint) by checking
    EVERY single candle in the overlap period.
    """
    np.random.seed(42)
    periods = 120
    dates = pd.date_range(start="2026-01-01", periods=periods, freq="h")
    
    # Generate mock price data
    prices = 100.0 + np.cumsum(np.random.randn(periods) * 2.0)
    prices[35] = 160.0
    prices[65] = 40.0
    
    df_full = pd.DataFrame({
        "Open": prices - 1.0,
        "High": prices + 2.0,
        "Low": prices - 2.0,
        "Close": prices,
        "Volume": 1000.0
    }, index=dates)
    
    # Slice dataframe up to row 90
    slice_len = 90
    df_sliced = df_full.iloc[:slice_len].copy()
    
    # Calculate SMC on both sliced and full dataframes
    df_sliced_calc = calculate_smc_lite(df_sliced, window=20)
    df_full_calc = calculate_smc_lite(df_full, window=20)
    
    # Compare every single row in the overlap period (from index 0 to slice_len - 1)
    for idx in range(slice_len):
        support_sliced = df_sliced_calc.iloc[idx]["Support_Level"]
        support_full = df_full_calc.iloc[idx]["Support_Level"]
        
        resistance_sliced = df_sliced_calc.iloc[idx]["Resistance_Level"]
        resistance_full = df_full_calc.iloc[idx]["Resistance_Level"]
        
        source_support_sliced = df_sliced_calc.iloc[idx]["Support_Source"]
        source_support_full = df_full_calc.iloc[idx]["Support_Source"]
        
        source_resistance_sliced = df_sliced_calc.iloc[idx]["Resistance_Source"]
        source_resistance_full = df_full_calc.iloc[idx]["Resistance_Source"]
        
        # Verify no repainting occurred
        assert support_sliced == support_full, f"Support repainted at index {idx}! Sliced: {support_sliced}, Full: {support_full}"
        assert resistance_sliced == resistance_full, f"Resistance repainted at index {idx}! Sliced: {resistance_sliced}, Full: {resistance_full}"
        assert source_support_sliced == source_support_full, f"Support source changed at index {idx}!"
        assert source_resistance_sliced == source_resistance_full, f"Resistance source changed at index {idx}!"
