import datetime
from typing import List
from tradenexus.presets.preset_models import StrategyPreset

def get_builtin_presets() -> List[StrategyPreset]:
    """
    Returns the list of 7 built-in read-only presets.
    All use workspace_id='__builtin__' and is_builtin=1.
    """
    now_str = "2026-07-09T00:00:00Z"
    
    return [
        StrategyPreset(
            preset_id="conservative_trend_follower",
            workspace_id="__builtin__",
            name="Conservative Trend Follower",
            description="Low risk trend following setup on major high liquidity assets with strict rule verification.",
            asset_class="Forex/Indices",
            trading_style="Trend Following",
            risk_profile="Conservative",
            allowed_symbols=["GC=F", "^GSPC", "^IXIC", "BTC-USD"],
            allowed_timeframes=["1h", "4h", "1d"],
            allowed_sessions=["ASIAN", "LONDON", "NEWYORK"],
            allowed_setup_types=["TREND_FOLLOWING", "SMC_SUPPORT"],
            allowed_regimes=["BULL_TREND", "BEAR_TREND"],
            blocked_regimes=["CHOPPY", "RANGING"],
            min_confluence_score=75.0,
            min_rr=2.0,
            max_trades_per_day=3,
            max_losses_per_day=2,
            max_consecutive_losses=2,
            cooldown_minutes_after_loss=120,
            default_portfolio_risk_pct=0.5,
            suggested_symbols=["GC=F", "^GSPC", "EURUSD=X"],
            notes="Ideal for index and gold traders looking for high-probability setups.",
            tags=["Conservative", "Trend", "Strict"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        ),
        StrategyPreset(
            preset_id="balanced_swing_trader",
            workspace_id="__builtin__",
            name="Balanced Swing Trader",
            description="Standard setup designed to capture medium-term price swings over days or weeks.",
            asset_class="Equities/Crypto/Commodities",
            trading_style="Swing Trading",
            risk_profile="Moderate",
            allowed_symbols=["BTC-USD", "GC=F", "AAPL", "MSFT"],
            allowed_timeframes=["2h", "4h", "1d"],
            allowed_sessions=["ASIAN", "LONDON", "NEWYORK"],
            allowed_setup_types=["TREND_FOLLOWING", "REVERSAL"],
            allowed_regimes=["BULL_TREND", "BEAR_TREND", "RANGING"],
            blocked_regimes=["CHOPPY"],
            min_confluence_score=70.0,
            min_rr=1.5,
            max_trades_per_day=5,
            max_losses_per_day=3,
            max_consecutive_losses=3,
            cooldown_minutes_after_loss=60,
            default_portfolio_risk_pct=1.0,
            suggested_symbols=["BTC-USD", "AAPL", "MSFT", "GC=F"],
            notes="Standard settings with moderate risk limits, suitable for most market regimes.",
            tags=["Swing", "Balanced", "Moderate"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        ),
        StrategyPreset(
            preset_id="aggressive_momentum_breakout",
            workspace_id="__builtin__",
            name="Aggressive Momentum Breakout",
            description="High-frequency momentum strategy focusing on fast volatile breakout extensions.",
            asset_class="Crypto/Altcoins/Growth Stocks",
            trading_style="Breakout",
            risk_profile="Aggressive",
            allowed_symbols=["BTC-USD", "ETH-USD", "SOL-USD", "TSLA", "NVDA"],
            allowed_timeframes=["15m", "30m", "1h"],
            allowed_sessions=["ASIAN", "LONDON", "NEWYORK"],
            allowed_setup_types=["BREAKOUT", "MOMENTUM_RUN"],
            allowed_regimes=["BULL_TREND", "BEAR_TREND", "CHOPPY"],
            blocked_regimes=[],
            min_confluence_score=60.0,
            min_rr=1.2,
            max_trades_per_day=10,
            max_losses_per_day=5,
            max_consecutive_losses=4,
            cooldown_minutes_after_loss=30,
            default_portfolio_risk_pct=1.5,
            suggested_symbols=["BTC-USD", "ETH-USD", "NVDA"],
            notes="Aggressive settings for fast-paced markets. Requires tight risk execution checks.",
            tags=["Aggressive", "Momentum", "Breakout"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        ),
        StrategyPreset(
            preset_id="gold_intraday_scalper",
            workspace_id="__builtin__",
            name="Gold Intraday Scalper",
            description="Highly focused scalp setup dedicated to Gold futures during London/NY overlaps.",
            asset_class="Commodities",
            trading_style="Scalping",
            risk_profile="Moderate",
            allowed_symbols=["GC=F", "SI=F"],
            allowed_timeframes=["5m", "15m", "30m"],
            allowed_sessions=["LONDON", "NEWYORK"],
            allowed_setup_types=["SMC_SUPPORT", "REVERSAL"],
            allowed_regimes=["BULL_TREND", "BEAR_TREND", "RANGING"],
            blocked_regimes=["CHOPPY"],
            min_confluence_score=70.0,
            min_rr=1.5,
            max_trades_per_day=8,
            max_losses_per_day=4,
            max_consecutive_losses=3,
            cooldown_minutes_after_loss=15,
            default_portfolio_risk_pct=1.0,
            suggested_symbols=["GC=F"],
            notes="Restricted to London and New York session hours for maximum volume and execution speed.",
            tags=["Scalping", "Gold", "Session-Restricted"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        ),
        StrategyPreset(
            preset_id="crypto_247_momentum",
            workspace_id="__builtin__",
            name="Crypto 24/7 Momentum",
            description="Exploits cryptocurrency trends 24/7 with wider stop limits and breakout targets.",
            asset_class="Cryptocurrency",
            trading_style="Momentum",
            risk_profile="Aggressive",
            allowed_symbols=["BTC-USD", "ETH-USD", "SOL-USD"],
            allowed_timeframes=["1h", "4h"],
            allowed_sessions=["ASIAN", "LONDON", "NEWYORK"],
            allowed_setup_types=["TREND_FOLLOWING", "BREAKOUT"],
            allowed_regimes=["BULL_TREND", "BEAR_TREND"],
            blocked_regimes=["RANGING", "CHOPPY"],
            min_confluence_score=65.0,
            min_rr=1.5,
            max_trades_per_day=10,
            max_losses_per_day=5,
            max_consecutive_losses=4,
            cooldown_minutes_after_loss=45,
            default_portfolio_risk_pct=1.2,
            suggested_symbols=["BTC-USD", "ETH-USD"],
            notes="Ideal for continuously running scanners without timezone bounds.",
            tags=["Crypto", "24/7", "Momentum"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        ),
        StrategyPreset(
            preset_id="index_futures_session_trader",
            workspace_id="__builtin__",
            name="Index Futures Session Trader",
            description="Designed for S&P 500, Dow, and Nasdaq index futures trading during US regular hours.",
            asset_class="Indices",
            trading_style="Session Trading",
            risk_profile="Moderate",
            allowed_symbols=["^GSPC", "^IXIC", "^DJI", "^NDX"],
            allowed_timeframes=["15m", "1h"],
            allowed_sessions=["NEWYORK"],
            allowed_setup_types=["TREND_FOLLOWING", "REVERSAL"],
            allowed_regimes=["BULL_TREND", "BEAR_TREND"],
            blocked_regimes=["CHOPPY"],
            min_confluence_score=70.0,
            min_rr=1.5,
            max_trades_per_day=4,
            max_losses_per_day=2,
            max_consecutive_losses=2,
            cooldown_minutes_after_loss=60,
            default_portfolio_risk_pct=1.0,
            suggested_symbols=["^GSPC", "^NDX"],
            notes="Strictly filters entry setups to the US New York trading session only.",
            tags=["Indices", "Session", "NY"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        ),
        StrategyPreset(
            preset_id="research_backtest_only",
            workspace_id="__builtin__",
            name="Research / Backtest Only",
            description="Relaxed rules workspace preset for research backtests and sandbox simulations.",
            asset_class="Any",
            trading_style="Research/Backtest",
            risk_profile="High Allowance",
            allowed_symbols=[],
            allowed_timeframes=[],
            allowed_sessions=[],
            allowed_setup_types=[],
            allowed_regimes=[],
            blocked_regimes=[],
            min_confluence_score=50.0,
            min_rr=1.0,
            max_trades_per_day=99,
            max_losses_per_day=99,
            max_consecutive_losses=99,
            cooldown_minutes_after_loss=0,
            default_portfolio_risk_pct=2.0,
            suggested_symbols=[],
            notes="Lax discipline checks to permit wide backtest coverage and grid-safety comparisons.",
            tags=["Backtest", "Lax", "Research"],
            is_builtin=1,
            created_at=now_str,
            updated_at=now_str
        )
    ]
